### ISSUE TITLE
UICollectionReusableView support?

### ISSUE THREAD

**Issue by mariohahn** [klundberg/KRLCollectionViewGridLayout#1]
Is it possible to use UICollectionReusableView with your Layout?

**Comment by klundberg** [comment]
You mean as a supplementary or decoration view? Not yet, I intend to at some point implement headers and footers like how flow layout does it but it's not there right now. 

-Kevin

**Comment by mariohahn** [comment]
Would be awesome!!! 

thanks

**Comment by klundberg** [comment]
This is now available in v0.2.0
