### ISSUE TITLE
Carthage is not working

### ISSUE THREAD

**Issue by eMdOS** [klundberg/KRLCollectionViewGridLayout#6]
When executing `carthage update --platform iOS`, I'm getting the following log:

**\* Cloning KRLCollectionViewFlowLayout
A shell task failed with exit code 128:
remote: Repository not found.
fatal: repository 'https://github.com/klundberg/KRLCollectionViewFlowLayout.git/' not found

**Comment by klundberg** [comment]
Looks like a possible network issue with Carthage. Does this consistently fail for this repo, and does it work with other repos? What does your Cartfile look like, also?

**Comment by eMdOS** [comment]
Nope, I don't think so.

Regarding to `Cartfile`:

If I add `github "klundberg/KRLCollectionViewFlowLayout" ~> 0.4.1` (what it supposed to work), it fails...
But it works if I add `git "git@github.com:klundberg/KRLCollectionViewGridLayout.git"` instead. This is what fixes the issue.

So, it is not a network issue.

**Comment by klundberg** [comment]
Oh, I'm sorry! My carthage directions have a typo. instead of `github "klundberg/KRLCollectionViewFlowLayout" ~> 0.4.1` it should be `github "klundberg/KRLCollectionViewGridLayout" ~> 0.4.1`. I'll update this right away.

**Comment by eMdOS** [comment]
{^_^}
